Address #878. Fire SignalPromptPurchaseFinished on developer products
Roblox/Core-Scripts pull request #1006
Opened 2017-08-03 13:12 UTC by Quenty

Address issue #878: PromptProductPurchaseFinished is depreciated, but PromptPurchaseFinished does not fire for Developer products

#878

2017-08-03 15:39 UTC, ghost requested changes
~~I don't see how this solves #878. It will actually break non-developer product purchases since PromptPurchaseFinished will not fire if IsPurchasingConsumable.~~ I'm stupid. I didnt see the line of code under the If statement. But I still dont see how it solves #878.

2017-08-04 18:34 UTC, Quenty commented
It lets `PromptPurchaseFinished` fire for both normal and developer products, providing an official API. 

It's just firing an event when `PromptPurchaseFinished` occurs.

There should be another event to fire when a prompt shows up, but that's technically a new feature.

2017-08-15 13:29 UTC, stillunt1tled commented
@Quenty there are conflicts, please resolve.

2020-06-10 22:59 UTC, cliffchapmanrbx commented
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosen [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.

2020-06-10 22:59 UTC, closed without merging